import type { Strings } from './es'

/** Traducción inglesa; satisface la forma canónica `Strings` (D1). */
export const en: Strings = {
  app: {
    title: 'Agent Cost',
    subtitle: 'AI agent cost calculator (Anthropic, OpenAI, Google)',
  },
  providers: {
    selectorLabel: 'Model family',
    anthropic: 'Anthropic · Claude',
    openai: 'OpenAI · ChatGPT',
    google: 'Google · Gemini',
  },
  header: {
    providerLabel: 'Model family',
    presetsLabel: 'Preset scenarios',
    customized: (presetName: string) => `Customized (based on ${presetName})`,
    copyLink: 'Share',
    copied: 'Link copied',
    reset: 'Reset',
    resetAria: 'Reset the scenario to the default preset',
    themeToggle: 'Toggle light and dark mode',
    currencyLabel: 'Display currency',
    currencyEur: '€',
    currencyUsd: '$',
    currencyEurAria: 'Show figures in euros',
    currencyUsdAria: 'Show figures in dollars',
    languageLabel: 'Interface language',
  },
  staleVersion: (urlVersion: string, currentVersion: string) =>
    `This scenario was shared with pricing version ${urlVersion}; current prices are version ${currentVersion}. The calculation uses current prices.`,
  dismiss: 'Dismiss notice',
  tokens: {
    sectionTitle: 'Token I/O rate',
    sectionHint: 'Tokens consumed per active agent hour',
    input: {
      label: 'Fresh input',
      unit: 'k tok/h',
      help: 'Uncached input tokens the model reads for the first time. Example: 42k/h is like sending around 30 pages of new text every hour.',
    },
    output: {
      label: 'Output',
      unit: 'k tok/h',
      help: 'Tokens generated by the model, including reasoning (thinking). Example: 210k/h is about 150 pages generated per hour, code and reasoning included.',
    },
    cacheRead: {
      label: 'Cache read',
      unit: 'M tok/h',
      help: '30M cache read/h ≈ a ~150k-token average context reread across ~200 calls/hour. It is usually the dominant cost item: the lever is context engineering.',
    },
    cacheWrite: {
      label: 'Cache write',
      unit: 'k tok/h',
      help: 'Prompt cache writes (5 min TTL, 1.25× input rate). Example: 530k/h is like caching a ~150k-token context 3-4 times per hour.',
    },
    cachedInput: {
      label: 'Cached input',
      unit: 'M tok/h',
      help: 'Input tokens served from OpenAI’s cache at a reduced rate. Equivalent to cache read: repeated context the model rereads at a discounted price.',
    },
    cacheStorage: {
      label: 'Cached tokens retained',
      unit: 'M tok',
      help: 'Volume of tokens held in Gemini’s explicit cache. Billed by storage and scheduled hour, not per call. Only affects the monthly cost when you enable the storage term.',
    },
    helpButton: (label: string) => `Help about ${label}`,
    categoryDetail: (cost: string, share: string) => `${cost} · ${share} of blend`,
  },
  mix: {
    sectionTitle: 'Model mix',
    sectionHint:
      'Split of active time across models; the cheapest model takes the remainder up to 100%',
    haikuRest: 'remainder',
    blendLabel: 'Blend rate',
    rateLabel: (rate: string) => `${rate} active`,
    tabsLabel: 'Model family',
    perfLabel: 'Mix performance',
    scoreParen: (score: string) => `(${score})`,
  },
  schedule: {
    sectionTitle: 'Schedule and utilization',
    hoursPerDay: 'Hours per day',
    daysPerWeek: 'Days per week',
    dutyCycle: 'Duty cycle',
    agents: 'Number of agents',
    hoursUnit: 'h/day',
    daysUnit: 'days',
    dutyUnit: '%',
    agentsUnit: 'agents',
    regimes: { full: '24×7', extended: '12×5', office: '8×5' },
    regimeGroupLabel: 'Schedule presets',
    dutyHelp:
      'Fraction of scheduled time the agent actually consumes tokens. The rest is idle time (build/test waits, human approvals, inactivity) that does not bill. A 100% duty assumes the agent is continuously active; the weighted cost is the ceiling × duty cycle.',
    helpButton: (label: string) => `Help about ${label}`,
    contextLine: (scheduled: string, active: string, duty: string) =>
      `${scheduled}/month scheduled per agent · ${active} active at ${duty} duty`,
    dutyGuide:
      'Guide: supervised with a human in the loop ≈ 30–40% · agent in CI with build/test waits ≈ 50–65% · autonomous without approvals ≈ 75–85%',
  },
  metrics: {
    blend: 'Blend per active hour',
    ceiling: 'Monthly ceiling',
    weighted: 'Monthly weighted',
    weightedHint: 'ceiling × duty cycle',
    annual: 'Annual weighted',
    storage: 'Cache storage',
    storageHint: 'monthly cost separate from the blend',
    swePro: 'SWE-Pro performance',
    costPerPoint: 'Cost/point',
    costPerPointHint: 'monthly cost per SWE-Pro point',
  },
  performance: {
    approx: 'approximate',
    approxHint: 'Includes estimated scores or scores not published by the vendor: approximate value.',
    na: 'n/a',
    disclaimer:
      'SWE-bench Pro performance trusts each vendor’s own number and mixes bases (Scale standardized, vendor, and estimated). Each family uses its own scaffold, which inflates 15–30 points over the standardized one, so cross-family performance comparison is indicative, not an exact equivalence.',
  },
  charts: {
    breakdownTitle: 'Cost breakdown by token category',
    breakdownHint: 'Cost per active hour of the current blend',
    categories: {
      cacheRead: 'Cache read',
      output: 'Output',
      cacheWrite: 'Cache write',
      input: 'Fresh input',
      cachedInput: 'Cached input',
      cacheStorage: 'Storage',
    },
    ceilingVsWeightedTitle: 'Monthly ceiling vs. weighted',
    ceilingBar: 'Ceiling (100% duty)',
    weightedBar: 'Weighted (current duty)',
    tableCaption: 'Chart data in table form',
    colCategory: 'Category',
    colCost: (symbol: string) => `${symbol}/h`,
    colShare: '% of blend',
    tabsLabel: 'Results charts',
    tabBreakdown: 'Breakdown by token',
    tabCeiling: 'Ceiling vs. weighted cost',
  },
  salary: {
    sectionTitle: 'Comparison with employer cost',
    fxLabel: 'Exchange rate',
    fxUnit: '€ per USD',
    agentMonthly: (money: string) => `Scenario weighted cost: ${money}/month`,
    agentPerHour: (rate: string) => `Agent cost per active hour: ${rate}`,
    hoursLine: (agentHours: string, fteHours: string, ratio: string) =>
      `${agentHours} active/month in the scenario ≈ ${ratio} the ~${fteHours} effective/month of an FTE`,
    colProfile: 'Profile',
    colGross: 'Annual gross (€)',
    colEmployerYear: 'Employer cost/year',
    colEmployerMonth: 'Employer cost/month',
    colPerHour: (symbol: string) => `${symbol}/effective h`,
    colFte: 'FTE equivalence',
    fteValue: (ratio: string) => `≈ ${ratio}`,
    grossInputLabel: (profile: string) => `Annual gross of ${profile}`,
    chartTitle: (code: string) => `Monthly cost: agent scenario vs. profiles (${code})`,
    agentBarLabel: 'Agents (scenario)',
    disclaimer:
      'Salaries are indicative (national averages, no city premium or variable pay) and the employer-cost multiplier is an approximation. This comparison does not imply equivalent capabilities or substitutability: it is an order-of-magnitude reference for business cases.',
    multiplierNote: (multiplier: string, hours: string) =>
      `Employer cost = gross × ${multiplier} · ${hours} effective h/year`,
  },
  learnings: {
    label: 'What to watch',
  },
  advanced: {
    sectionTitle: 'Advanced configuration',
    sectionHint:
      'Batch API, long context, regional surcharge, cache storage, exchange rate, employer cost and editable prices',
    toggleExpand: 'Show or hide advanced configuration',
    pricingTitle: 'Prices per model (USD/MTok)',
    pricingHint: 'Edit the official rates; changes live only in this session and in the link.',
    pricingTabsLabel: 'Pricing family',
    restoreOfficial: 'Restore official',
    priceFields: {
      input: 'Input',
      output: 'Output',
      cache_read: 'Cache read',
      cache_write: 'Cache write',
      cached_input: 'Cached input',
      cache_storage: 'Storage /h',
    },
    priceCellAria: (model: string, field: string) => `${field} price of ${model} (USD/MTok)`,
    colModel: 'Model',
    batchTitle: 'Batch API (−50%)',
    batchToggle: 'Enable Batch API',
    batchHelp:
      'The Batch API processes requests asynchronously with a 50% discount. Indicate what fraction of the work does not require latency and can go through batch.',
    batchFractionLabel: '% of eligible work',
    batchUnit: '%',
    regionalTitle: 'Regional surcharge',
    regionalToggle: 'Enable regional surcharge',
    regionalHelp:
      'Some regions apply an approximate 10% surcharge across all token categories. Applies to Anthropic, OpenAI and Google (e.g. access via Amazon Bedrock or regional residency endpoints).',
    storageTitle: 'Cache storage (Gemini)',
    storageToggle: 'Enable cache storage cost',
    storageHelp:
      'Gemini bills explicit cache by storage and scheduled hour, on top of reads. Enable it and set the retained tokens to include that monthly cost.',
    storageDisclaimer:
      'Gemini’s explicit cache is an estimate: storage cost is modeled separately from the hourly blend and assumes you retain that volume for all scheduled hours.',
    longContextTitle: 'Long context',
    longContextToggle: 'Enable long context',
    longContextHelp:
      'Above an input threshold (≈200K on Gemini Pro, ≈272K on GPT) the native API charges a surcharge. Set what fraction of work exceeds that threshold. Anthropic serves 1M at a flat rate, so it does not apply.',
    longContextFractionLabel: '% of work in long context',
    longContextUnit: '%',
    longContextNotApplicable:
      'This family has no long-context surcharge: this setting does not affect its cost.',
    copilotToggle: 'Via GitHub Copilot',
    copilotHelp:
      'In GitHub Copilot’s AI Credits redemption, the long-context tier of some OpenAI and Gemini models costs more than the native API. Enable it to apply those higher rates to the long-context fraction.',
    fxLabel: 'Exchange rate',
    fxUnit: '€ per USD',
    employerMultiplierLabel: 'Employer-cost multiplier',
    employerMultiplierHelp:
      'Factor that converts annual gross into total employer cost (social security, equipment, etc.). Default 1.30.',
    effectiveHoursLabel: 'Annual effective hours (FTE)',
    effectiveHoursUnit: 'h/year',
    effectiveHoursHelp:
      'Hours a full-time employee is actually productive per year, excluding holidays, public holidays and non-billable time. Default 1,720.',
  },
  badges: {
    batch: (percent: string) => `batch ${percent} applied`,
    regional: 'Regional +10%',
    storage: 'cache storage',
    longContext: (percent: string) => `long context ${percent}`,
    longContextCopilot: (percent: string) => `long context ${percent} · Copilot`,
    pricesEdited: 'prices edited',
    label: 'Active modifiers',
  },
  presentation: {
    toggle: 'Presentation',
    toggleAria: 'Enable or disable presentation mode',
    exit: 'Calculator',
  },
  exporting: {
    sectionTitle: 'Export',
    menuAria: 'Export options',
    json: 'Export JSON',
    csv: 'Export CSV',
    pngChart: 'Export image',
    pngChartAria: (chart: string) => `Export ${chart} as a PNG image`,
    pngAll: 'Export all (PNG)',
    fileBase: 'agentcost-scenario',
    csvColKey: 'key',
    csvColValue: 'value',
    fields: {
      preset: 'preset',
      parameters: 'parameters',
      modifiers: 'modifiers',
      results: 'results',
    },
  },
  footer: {
    pricingVersion: (version: string, date: string) =>
      `API prices version ${version} (effective from ${date})`,
    pricingSourcesLabel: 'Official pricing tables',
    salarySources: (sources: string, reviewed: string) =>
      `Defaults (Spain), editable · Sources: ${sources} · Last reviewed: ${reviewed}`,
    estimateDisclaimer:
      'All figures are indicative estimates based on the parameters entered; they are not a billing forecast.',
    noBackend: '100% static tool: no data leaves your browser.',
    observationsLabel: 'Notes',
  },
  presets: {
    p1: {
      name: 'Supervised pair programming',
      description:
        'A developer works with a Claude Code-style agent in an interactive session. The human reviews and approves; the agent spends most of the time waiting. Token profile representative of an interactive development session.',
      learnings:
        'The low duty (the agent waits for the human) makes the real cost a fraction of the ceiling: the lever here is how much of the scheduled time actually bills, not the hourly rate.',
    },
    p2: {
      name: 'Balanced delivery agent',
      description:
        'Agent embedded in a team workflow: Opus plans the feature and reviews the final PR, Sonnet implements, Haiku runs the test/lint cycle. Runs continuously serving a task queue with build and CI waits.',
      learnings:
        'Cache read concentrates most of the hourly cost; the savings lever is context engineering, not switching models.',
    },
    p3: {
      name: 'Design-intensive / greenfield',
      description:
        'Product kickoff or complex architecture: the frontier model (Fable) and Opus carry the weight of design, ADRs and deep review; Sonnet prototypes. High output from documents and extensive reasoning. Workday with frequent supervision.',
      learnings:
        'The only scenario with the frontier model: that slice, on top of Opus weight, drives up the hourly rate versus Sonnet-first scenarios with similar tokens. The lever is how much of the reasoning can move down to Sonnet without losing design quality.',
    },
    p4: {
      name: 'Maintenance on mature code',
      description:
        'Maintenance and enhancements on mature code: Sonnet resolves most tasks and Opus only steps in as an escalation when the agent gets stuck. Haiku absorbs the trivial work. High autonomy.',
      learnings:
        'With Sonnet-first and Haiku absorbing the trivial work, the hourly rate drops; the monthly cost is set by the high duty and the 24×7 schedule, not by the model price.',
    },
    p5: {
      name: 'Nightly QA swarm',
      description:
        'A fleet of testing agents (synthetic personas, E2E regression, evals and vulnerability analysis) that runs off-hours. Mostly Haiku-heavy in short contexts, with a slice of the frontier model (Fable) for deep security analysis. An ideal Batch API (−50%) candidate since it needs no latency.',
      learnings:
        'The Batch API (−50%) over the 80% eligible is the biggest savings lever and cost scales linearly with the number of agents; even so, a mere 5% slice of Fable for security analysis is enough to concentrate ~¼ of the hourly cost: watch how much work you route to the frontier model.',
    },
    p6: {
      name: 'Autonomous maintenance agent',
      description:
        'An agent with no human in the loop that triages issues, updates dependencies and opens PRs 24×7. High duty since it waits for no approvals; large context from extensive repos — cache read dominates the cost.',
      learnings:
        'Cache read concentrates >70% of the cost — the lever is context engineering, not the model. The high duty, waiting for no approvals, brings the monthly cost close to the ceiling.',
    },
    o1: {
      name: 'Supervised pair programming',
      description:
        'A developer works with a ChatGPT-based agent in an interactive session. GPT-5.4 mini carries the bulk and GPT-5.4 nano the trivial work; the human reviews and approves, with low duty.',
      learnings:
        'The low duty (the agent waits for the human) makes the real cost a fraction of the ceiling: the lever is how much of the scheduled time bills, not the rate.',
    },
    o2: {
      name: 'Balanced delivery agent',
      description:
        'Agent embedded in a team workflow: GPT-5.4 plans and reviews the PR, GPT-5.4 mini implements and GPT-5.4 nano runs tests and lint. Runs continuously serving a queue with CI waits.',
      learnings:
        'Cached input concentrates much of the hourly cost; the lever is context engineering and reusing cached prompt, not switching models.',
    },
    o3: {
      name: 'Design-intensive / greenfield',
      description:
        'Product kickoff: GPT-5.5 (frontier) and GPT-5.4 carry design, ADRs and deep review; GPT-5.4 mini prototypes. High output from documents and extensive reasoning, with frequent supervision.',
      learnings:
        'The only scenario with the frontier model (GPT-5.5): that slice drives up the hourly rate versus mini-first scenarios. The lever is how much reasoning moves down to mini without losing quality.',
    },
    o4: {
      name: 'Maintenance on mature code',
      description:
        'Maintenance on mature code: GPT-5.4 mini resolves most tasks and GPT-5.4 only steps in as escalation; GPT-5.4 nano absorbs the trivial work. High 24×7 autonomy.',
      learnings:
        'With mini-first and nano absorbing the trivial work the hourly rate drops; the monthly cost is set by the high duty and the 24×7 schedule, not the model price.',
    },
    o5: {
      name: 'Nightly QA swarm',
      description:
        'A fleet of testing agents running off-hours, mostly GPT-5.4 nano in short contexts with a slice of GPT-5.5 for security analysis. An ideal Batch API (−50%) candidate.',
      learnings:
        'The Batch API (−50%) over the 80% eligible is the biggest lever and cost scales with the number of agents; even so, a 5% slice of GPT-5.5 concentrates hourly cost: watch how much you route to the frontier.',
    },
    o6: {
      name: 'Autonomous maintenance agent',
      description:
        'An agent with no human in the loop that triages issues, updates dependencies and opens PRs 24×7 on ChatGPT. High duty waiting for no approvals; large context with cached input dominant.',
      learnings:
        'Cached input concentrates the cost — the lever is context engineering. The high duty, waiting for no approvals, brings the monthly cost close to the ceiling.',
    },
    g1: {
      name: 'Supervised pair programming',
      description:
        'A developer works with a Gemini-based agent in an interactive session. Gemini 3.5 Flash carries the bulk and Flash-Lite the trivial work; the human reviews and approves, with low duty.',
      learnings:
        'The low duty (the agent waits for the human) makes the real cost a fraction of the ceiling: the lever is how much of the scheduled time bills, not the rate.',
    },
    g2: {
      name: 'Balanced delivery agent',
      description:
        'Agent embedded in the workflow: Gemini 3.1 Pro plans and reviews, Gemini 3.5 Flash implements and Flash-Lite runs tests. Runs continuously serving a queue with CI waits.',
      learnings:
        'Cache read concentrates much of the hourly cost; if you enable explicit storage, remember it bills per retained hour separately from the blend.',
    },
    g3: {
      name: 'Design-intensive / greenfield',
      description:
        'Product kickoff: Gemini 3.1 Pro carries design, ADRs and deep review; Gemini 3.5 Flash prototypes. High output from documents and extensive reasoning, with frequent supervision.',
      learnings:
        'The weight of Gemini 3.1 Pro (frontier, Preview) drives up the hourly rate versus Flash-first scenarios. The lever is how much reasoning moves down to Flash without losing design quality.',
    },
    g4: {
      name: 'Maintenance on mature code',
      description:
        'Maintenance on mature code: Gemini 3.5 Flash resolves most tasks and Gemini 3.1 Pro only escalates; Flash-Lite absorbs the trivial work. High 24×7 autonomy.',
      learnings:
        'With Flash-first and Flash-Lite absorbing the trivial work the hourly rate drops; the monthly cost is set by the high duty and the 24×7 schedule, not the model price.',
    },
    g5: {
      name: 'Nightly QA swarm',
      description:
        'A fleet of testing agents running off-hours, mostly Flash-Lite in short contexts with a slice of Gemini 3.1 Pro for security analysis. An ideal Batch API (−50%) candidate.',
      learnings:
        'The Batch API (−50%) over the 80% eligible is the biggest lever and cost scales with the number of agents; a 5% slice of Gemini 3.1 Pro concentrates hourly cost: watch how much you route to the frontier.',
    },
    g6: {
      name: 'Autonomous maintenance agent',
      description:
        'An agent with no human in the loop that triages issues, updates dependencies and opens PRs 24×7 on Gemini. High duty waiting for no approvals; large context with cache read dominant.',
      learnings:
        'Cache read concentrates the cost — the lever is context engineering. The high duty, waiting for no approvals, brings the monthly cost close to the ceiling.',
    },
  },
  salaryRoles: {
    junior: { name: 'Junior', experience: '0–2 years' },
    mid: { name: 'Mid', experience: '2–5 years' },
    senior: { name: 'Senior', experience: '5+ years' },
    techlead: { name: 'Tech Lead / Architect', experience: '8+ years' },
  },
  salarySource:
    'Glassdoor Spain, InfoJobs ICT Report, LinkedIn Salary Insights, INE Wage Structure Survey',
}
